# Generated by Django 5.0.3 on 2024-04-02 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Password',
            new_name='City',
        ),
    ]
