# Generated by Django 5.0.3 on 2024-04-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_password_student_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Add',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
