# Generated by Django 5.0.3 on 2024-04-02 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_student_add'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['Name']},
        ),
    ]
